// Quiz data (195 unique countries)
const quizData = [
  { flag: "https://flagcdn.com/w320/us.png", country: "United States", options: ["Canada", "United States", "Australia", "United Kingdom"] },
  { flag: "https://flagcdn.com/w320/ca.png", country: "Canada", options: ["Mexico", "Canada", "United States", "Brazil"] },
  { flag: "https://flagcdn.com/w320/mx.png", country: "Mexico", options: ["Chile", "Mexico", "United States", "Cuba"] },
  { flag: "https://flagcdn.com/w320/br.png", country: "Brazil", options: ["Argentina", "Peru", "Brazil", "Colombia"] },
  { flag: "https://flagcdn.com/w320/ar.png", country: "Argentina", options: ["Uruguay", "Argentina", "Brazil", "Paraguay"] },
  { flag: "https://flagcdn.com/w320/cl.png", country: "Chile", options: ["Chile", "Bolivia", "Peru", "Argentina"] },
  { flag: "https://flagcdn.com/w320/co.png", country: "Colombia", options: ["Venezuela", "Ecuador", "Colombia", "Peru"] },
  { flag: "https://flagcdn.com/w320/pe.png", country: "Peru", options: ["Chile", "Ecuador", "Bolivia", "Peru"] },
  { flag: "https://flagcdn.com/w320/ve.png", country: "Venezuela", options: ["Colombia", "Ecuador", "Venezuela", "Peru"] },
  { flag: "https://flagcdn.com/w320/bo.png", country: "Bolivia", options: ["Paraguay", "Bolivia", "Peru", "Chile"] },
  { flag: "https://flagcdn.com/w320/ec.png", country: "Ecuador", options: ["Colombia", "Ecuador", "Peru", "Venezuela"] },
  { flag: "https://flagcdn.com/w320/uy.png", country: "Uruguay", options: ["Uruguay", "Argentina", "Paraguay", "Brazil"] },
  { flag: "https://flagcdn.com/w320/py.png", country: "Paraguay", options: ["Paraguay", "Bolivia", "Argentina", "Brazil"] },
  { flag: "https://flagcdn.com/w320/gb.png", country: "United Kingdom", options: ["Ireland", "United Kingdom", "Netherlands", "France"] },
  { flag: "https://flagcdn.com/w320/fr.png", country: "France", options: ["Belgium", "France", "Spain", "Germany"] },
  { flag: "https://flagcdn.com/w320/de.png", country: "Germany", options: ["Austria", "Germany", "Switzerland", "Netherlands"] },
  { flag: "https://flagcdn.com/w320/it.png", country: "Italy", options: ["Greece", "France", "Spain", "Italy"] },
  { flag: "https://flagcdn.com/w320/es.png", country: "Spain", options: ["Portugal", "France", "Spain", "Italy"] },
  { flag: "https://flagcdn.com/w320/pt.png", country: "Portugal", options: ["Spain", "Italy", "Portugal", "France"] },
  { flag: "https://flagcdn.com/w320/nl.png", country: "Netherlands", options: ["Belgium", "Netherlands", "Germany", "Sweden"] },
  { flag: "https://flagcdn.com/w320/be.png", country: "Belgium", options: ["Belgium", "France", "Germany", "Netherlands"] },
  { flag: "https://flagcdn.com/w320/ch.png", country: "Switzerland", options: ["Austria", "Switzerland", "Germany", "Italy"] },
  { flag: "https://flagcdn.com/w320/at.png", country: "Austria", options: ["Switzerland", "Austria", "Germany", "Czech Republic"] },
  { flag: "https://flagcdn.com/w320/se.png", country: "Sweden", options: ["Finland", "Sweden", "Norway", "Denmark"] },
  { flag: "https://flagcdn.com/w320/no.png", country: "Norway", options: ["Norway", "Sweden", "Finland", "Denmark"] },
  { flag: "https://flagcdn.com/w320/dk.png", country: "Denmark", options: ["Norway", "Denmark", "Sweden", "Finland"] },
  { flag: "https://flagcdn.com/w320/fi.png", country: "Finland", options: ["Finland", "Sweden", "Norway", "Denmark"] },
  { flag: "https://flagcdn.com/w320/is.png", country: "Iceland", options: ["Ireland", "Norway", "Iceland", "Finland"] },
  { flag: "https://flagcdn.com/w320/ie.png", country: "Ireland", options: ["Ireland", "United Kingdom", "Iceland", "Netherlands"] },
  { flag: "https://flagcdn.com/w320/pl.png", country: "Poland", options: ["Czech Republic", "Germany", "Poland", "Ukraine"] },
  { flag: "https://flagcdn.com/w320/cz.png", country: "Czech Republic", options: ["Slovakia", "Czech Republic", "Austria", "Poland"] },
  { flag: "https://flagcdn.com/w320/sk.png", country: "Slovakia", options: ["Czech Republic", "Hungary", "Slovakia", "Austria"] },
  { flag: "https://flagcdn.com/w320/hu.png", country: "Hungary", options: ["Austria", "Hungary", "Romania", "Slovakia"] },
  { flag: "https://flagcdn.com/w320/ro.png", country: "Romania", options: ["Bulgaria", "Romania", "Hungary", "Moldova"] },
  { flag: "https://flagcdn.com/w320/bg.png", country: "Bulgaria", options: ["Serbia", "Romania", "Bulgaria", "Greece"] },
  { flag: "https://flagcdn.com/w320/gr.png", country: "Greece", options: ["Italy", "Bulgaria", "Turkey", "Greece"] },
  { flag: "https://flagcdn.com/w320/tr.png", country: "Turkey", options: ["Turkey", "Greece", "Cyprus", "Bulgaria"] },
  { flag: "https://flagcdn.com/w320/cy.png", country: "Cyprus", options: ["Cyprus", "Greece", "Turkey", "Malta"] },
  { flag: "https://flagcdn.com/w320/mt.png", country: "Malta", options: ["Italy", "Malta", "Cyprus", "Greece"] },
  { flag: "https://flagcdn.com/w320/ru.png", country: "Russia", options: ["Ukraine", "Russia", "Belarus", "Kazakhstan"] },
  { flag: "https://flagcdn.com/w320/ua.png", country: "Ukraine", options: ["Ukraine", "Belarus", "Russia", "Poland"] },
  { flag: "https://flagcdn.com/w320/by.png", country: "Belarus", options: ["Lithuania", "Ukraine", "Belarus", "Russia"] },
  { flag: "https://flagcdn.com/w320/lt.png", country: "Lithuania", options: ["Latvia", "Estonia", "Lithuania", "Poland"] },
  { flag: "https://flagcdn.com/w320/lv.png", country: "Latvia", options: ["Estonia", "Lithuania", "Latvia", "Poland"] },
  { flag: "https://flagcdn.com/w320/ee.png", country: "Estonia", options: ["Estonia", "Latvia", "Finland", "Lithuania"] },
  { flag: "https://flagcdn.com/w320/md.png", country: "Moldova", options: ["Romania", "Moldova", "Ukraine", "Bulgaria"] },
  { flag: "https://flagcdn.com/w320/al.png", country: "Albania", options: ["Greece", "Albania", "North Macedonia", "Serbia"] },
  { flag: "https://flagcdn.com/w320/rs.png", country: "Serbia", options: ["Croatia", "Serbia", "Bosnia and Herzegovina", "Montenegro"] },
  { flag: "https://flagcdn.com/w320/hr.png", country: "Croatia", options: ["Croatia", "Slovenia", "Serbia", "Bosnia and Herzegovina"] },
  { flag: "https://flagcdn.com/w320/ba.png", country: "Bosnia and Herzegovina", options: ["Serbia", "Bosnia and Herzegovina", "Montenegro", "Croatia"] },
  { flag: "https://flagcdn.com/w320/si.png", country: "Slovenia", options: ["Slovakia", "Croatia", "Slovenia", "Austria"] },
  { flag: "https://flagcdn.com/w320/mk.png", country: "North Macedonia", options: ["Greece", "North Macedonia", "Albania", "Serbia"] },
  { flag: "https://flagcdn.com/w320/me.png", country: "Montenegro", options: ["Montenegro", "Serbia", "Bosnia and Herzegovina", "Albania"] },
  { flag: "https://upload.wikimedia.org/wikipedia/commons/1/1f/Flag_of_Kosovo.svg", country: "Kosovo", options: ["Kosovo", "Serbia", "Albania", "North Macedonia"] },
  { flag: "https://flagcdn.com/w320/lu.png", country: "Luxembourg", options: ["Luxembourg", "Belgium", "France", "Germany"] },
  { flag: "https://flagcdn.com/w320/ad.png", country: "Andorra", options: ["Andorra", "France", "Spain", "Monaco"] },
  { flag: "https://flagcdn.com/w320/mc.png", country: "Monaco", options: ["Monaco", "San Marino", "Andorra", "France"] },
  { flag: "https://flagcdn.com/w320/sm.png", country: "San Marino", options: ["San Marino", "Monaco", "Italy", "Vatican City"] },
  { flag: "https://flagcdn.com/w320/va.png", country: "Vatican City", options: ["Italy", "Monaco", "Vatican City", "San Marino"] },
  { flag: "https://flagcdn.com/w320/li.png", country: "Liechtenstein", options: ["Austria", "Switzerland", "Liechtenstein", "Germany"] },
  { flag: "https://flagcdn.com/w320/ge.png", country: "Georgia", options: ["Armenia", "Azerbaijan", "Georgia", "Turkey"] },
  { flag: "https://flagcdn.com/w320/am.png", country: "Armenia", options: ["Armenia", "Georgia", "Azerbaijan", "Iran"] },
  { flag: "https://flagcdn.com/w320/az.png", country: "Azerbaijan", options: ["Azerbaijan", "Armenia", "Georgia", "Turkey"] },
  { flag: "https://flagcdn.com/w320/kz.png", country: "Kazakhstan", options: ["Kazakhstan", "Uzbekistan", "Russia", "Kyrgyzstan"] },
  { flag: "https://flagcdn.com/w320/uz.png", country: "Uzbekistan", options: ["Kazakhstan", "Uzbekistan", "Turkmenistan", "Kyrgyzstan"] },
  { flag: "https://flagcdn.com/w320/tm.png", country: "Turkmenistan", options: ["Uzbekistan", "Afghanistan", "Turkmenistan", "Iran"] },
  { flag: "https://flagcdn.com/w320/kg.png", country: "Kyrgyzstan", options: ["Kyrgyzstan", "Kazakhstan", "Tajikistan", "Uzbekistan"] },
  { flag: "https://flagcdn.com/w320/tj.png", country: "Tajikistan", options: ["Afghanistan", "Tajikistan", "Kyrgyzstan", "Uzbekistan"] },
  { flag: "https://flagcdn.com/w320/af.png", country: "Afghanistan", options: ["Afghanistan", "Pakistan", "Iran", "Tajikistan"] },
  { flag: "https://flagcdn.com/w320/pk.png", country: "Pakistan", options: ["India", "Pakistan", "Afghanistan", "Bangladesh"] },
  { flag: "https://flagcdn.com/w320/bd.png", country: "Bangladesh", options: ["Bangladesh", "India", "Nepal", "Bhutan"] },
  { flag: "https://flagcdn.com/w320/bt.png", country: "Bhutan", options: ["Nepal", "Bhutan", "India", "Bangladesh"] },
  { flag: "https://flagcdn.com/w320/lk.png", country: "Sri Lanka", options: ["India", "Sri Lanka", "Maldives", "Bangladesh"] },
  { flag: "https://flagcdn.com/w320/mv.png", country: "Maldives", options: ["Sri Lanka", "India", "Maldives", "Indonesia"] },
  { flag: "https://flagcdn.com/w320/mm.png", country: "Myanmar", options: ["Thailand", "Myanmar", "Laos", "India"] },
  { flag: "https://flagcdn.com/w320/th.png", country: "Thailand", options: ["Cambodia", "Laos", "Myanmar", "Thailand"] },
  { flag: "https://flagcdn.com/w320/la.png", country: "Laos", options: ["Laos", "Thailand", "Cambodia", "Vietnam"] },
  { flag: "https://flagcdn.com/w320/kh.png", country: "Cambodia", options: ["Cambodia", "Laos", "Vietnam", "Thailand"] },
  { flag: "https://flagcdn.com/w320/vn.png", country: "Vietnam", options: ["Vietnam", "Cambodia", "Thailand", "Laos"] },
  { flag: "https://flagcdn.com/w320/cn.png", country: "China", options: ["China", "Mongolia", "Japan", "South Korea"] },
  { flag: "https://flagcdn.com/w320/mn.png", country: "Mongolia", options: ["Mongolia", "China", "Russia", "Kazakhstan"] },
  { flag: "https://flagcdn.com/w320/kr.png", country: "South Korea", options: ["South Korea", "Japan", "China", "North Korea"] },
  { flag: "https://flagcdn.com/w320/kp.png", country: "North Korea", options: ["North Korea", "China", "Japan", "South Korea"] },
  { flag: "https://flagcdn.com/w320/jp.png", country: "Japan", options: ["China", "South Korea", "Japan", "Vietnam"] },
  { flag: "https://flagcdn.com/w320/tw.png", country: "Taiwan", options: ["Philippines", "China", "Japan", "Taiwan"] },
  { flag: "https://flagcdn.com/w320/ph.png", country: "Philippines", options: ["Indonesia", "Philippines", "Malaysia", "Vietnam"] },
  { flag: "https://flagcdn.com/w320/id.png", country: "Indonesia", options: ["Indonesia", "Malaysia", "Philippines", "Singapore"] },
  { flag: "https://flagcdn.com/w320/my.png", country: "Malaysia", options: ["Malaysia", "Singapore", "Thailand", "Indonesia"] },
  { flag: "https://flagcdn.com/w320/sg.png", country: "Singapore", options: ["Singapore", "Malaysia", "Indonesia", "Thailand"] },
  { flag: "https://flagcdn.com/w320/bn.png", country: "Brunei", options: ["Malaysia", "Brunei", "Singapore", "Indonesia"] },
  { flag: "https://flagcdn.com/w320/tl.png", country: "Timor-Leste", options: ["Indonesia", "Timor-Leste", "Papua New Guinea", "Australia"] },
  { flag: "https://flagcdn.com/w320/pw.png", country: "Palau", options: ["Palau", "Micronesia", "Marshall Islands", "Nauru"] },
  { flag: "https://flagcdn.com/w320/fm.png", country: "Micronesia", options: ["Palau", "Micronesia", "Nauru", "Marshall Islands"] },
  { flag: "https://flagcdn.com/w320/mh.png", country: "Marshall Islands", options: ["Marshall Islands", "Micronesia", "Palau", "Nauru"] },
  { flag: "https://flagcdn.com/w320/nr.png", country: "Nauru", options: ["Kiribati", "Nauru", "Micronesia", "Marshall Islands"] },
  { flag: "https://flagcdn.com/w320/ki.png", country: "Kiribati", options: ["Kiribati", "Nauru", "Fiji", "Tuvalu"] },
  { flag: "https://flagcdn.com/w320/tv.png", country: "Tuvalu", options: ["Tuvalu", "Fiji", "Kiribati", "Vanuatu"] },
  { flag: "https://flagcdn.com/w320/fj.png", country: "Fiji", options: ["Fiji", "Vanuatu", "Samoa", "Tonga"] },
  { flag: "https://flagcdn.com/w320/ws.png", country: "Samoa", options: ["Tonga", "Samoa", "Fiji", "Vanuatu"] },
  { flag: "https://flagcdn.com/w320/to.png", country: "Tonga", options: ["Samoa", "Tonga", "Fiji", "Vanuatu"] },
  { flag: "https://flagcdn.com/w320/vu.png", country: "Vanuatu", options: ["Fiji", "Vanuatu", "Solomon Islands", "Papua New Guinea"] },
  { flag: "https://flagcdn.com/w320/sb.png", country: "Solomon Islands", options: ["Vanuatu", "Solomon Islands", "Papua New Guinea", "Fiji"] },
  { flag: "https://flagcdn.com/w320/pg.png", country: "Papua New Guinea", options: ["Solomon Islands", "Australia", "Papua New Guinea", "Vanuatu"] },
  { flag: "https://flagcdn.com/w320/au.png", country: "Australia", options: ["New Zealand", "Australia", "Papua New Guinea", "Fiji"] },
  { flag: "https://flagcdn.com/w320/nz.png", country: "New Zealand", options: ["New Zealand", "Australia", "Fiji", "Tonga"] },
  { flag: "https://flagcdn.com/w320/nc.png", country: "New Caledonia", options: ["Vanuatu", "New Caledonia", "Fiji", "Solomon Islands"] },
  { flag: "https://flagcdn.com/w320/pf.png", country: "French Polynesia", options: ["French Polynesia", "Samoa", "Fiji", "Tonga"] },
  { flag: "https://flagcdn.com/w320/wf.png", country: "Wallis and Futuna", options: ["Wallis and Futuna", "Samoa", "Fiji", "Tonga"] },
  { flag: "https://flagcdn.com/w320/ck.png", country: "Cook Islands", options: ["Cook Islands", "Samoa", "Tonga", "Fiji"] },
  { flag: "https://flagcdn.com/w320/nu.png", country: "Niue", options: ["Niue", "Cook Islands", "Samoa", "Tonga"] },
  { flag: "https://flagcdn.com/w320/tk.png", country: "Tokelau", options: ["Tokelau", "Samoa", "Niue", "Cook Islands"] },
  { flag: "https://flagcdn.com/w320/hk.png", country: "Hong Kong", options: ["Hong Kong", "Macau", "Taiwan", "China"] },
  { flag: "https://flagcdn.com/w320/mo.png", country: "Macau", options: ["Hong Kong", "Macau", "China", "Taiwan"] },
  { flag: "https://flagcdn.com/w320/np.png", country: "Nepal", options: ["Nepal", "Bhutan", "India", "Bangladesh"] },
  { flag: "https://flagcdn.com/w320/in.png", country: "India", options: ["Pakistan", "Bangladesh", "Nepal", "India"] },
  { flag: "https://flagcdn.com/w320/ir.png", country: "Iran", options: ["Afghanistan", "Iran", "Iraq", "Turkey"] },
  { flag: "https://flagcdn.com/w320/iq.png", country: "Iraq", options: ["Iran", "Iraq", "Syria", "Turkey"] },
  { flag: "https://flagcdn.com/w320/sy.png", country: "Syria", options: ["Lebanon", "Syria", "Iraq", "Jordan"] },
  { flag: "https://flagcdn.com/w320/lb.png", country: "Lebanon", options: ["Syria", "Lebanon", "Israel", "Jordan"] },
  { flag: "https://flagcdn.com/w320/jo.png", country: "Jordan", options: ["Syria", "Jordan", "Iraq", "Israel"] },
  { flag: "https://flagcdn.com/w320/il.png", country: "Israel", options: ["Jordan", "Israel", "Lebanon", "Egypt"] },
  { flag: "https://flagcdn.com/w320/ps.png", country: "Palestine", options: ["Palestine", "Israel", "Jordan", "Egypt"] },
  { flag: "https://flagcdn.com/w320/sa.png", country: "Saudi Arabia", options: ["Yemen", "Saudi Arabia", "Oman", "UAE"] },
  { flag: "https://flagcdn.com/w320/ye.png", country: "Yemen", options: ["Oman", "Yemen", "Saudi Arabia", "UAE"] },
  { flag: "https://flagcdn.com/w320/om.png", country: "Oman", options: ["UAE", "Oman", "Saudi Arabia", "Yemen"] },
  { flag: "https://flagcdn.com/w320/ae.png", country: "United Arab Emirates", options: ["UAE", "Oman", "Qatar", "Bahrain"] },
  { flag: "https://flagcdn.com/w320/qa.png", country: "Qatar", options: ["Kuwait", "Qatar", "UAE", "Bahrain"] },
  { flag: "https://flagcdn.com/w320/bh.png", country: "Bahrain", options: ["Bahrain", "Qatar", "UAE", "Kuwait"] },
  { flag: "https://flagcdn.com/w320/kw.png", country: "Kuwait", options: ["Kuwait", "Qatar", "Saudi Arabia", "Bahrain"] },
  { flag: "https://flagcdn.com/w320/eg.png", country: "Egypt", options: ["Sudan", "Libya", "Egypt", "Israel"] },
  { flag: "https://flagcdn.com/w320/sd.png", country: "Sudan", options: ["Sudan", "Egypt", "Ethiopia", "South Sudan"] },
  { flag: "https://flagcdn.com/w320/ss.png", country: "South Sudan", options: ["Sudan", "Ethiopia", "Uganda", "South Sudan"] },
  { flag: "https://flagcdn.com/w320/et.png", country: "Ethiopia", options: ["Eritrea", "Ethiopia", "Somalia", "Sudan"] },
  { flag: "https://flagcdn.com/w320/er.png", country: "Eritrea", options: ["Ethiopia", "Eritrea", "Sudan", "Djibouti"] },
  { flag: "https://flagcdn.com/w320/dj.png", country: "Djibouti", options: ["Eritrea", "Ethiopia", "Djibouti", "Somalia"] },
  { flag: "https://flagcdn.com/w320/so.png", country: "Somalia", options: ["Somalia", "Ethiopia", "Kenya", "Djibouti"] },
  { flag: "https://flagcdn.com/w320/ke.png", country: "Kenya", options: ["Tanzania", "Uganda", "Kenya", "Ethiopia"] },
  { flag: "https://flagcdn.com/w320/ug.png", country: "Uganda", options: ["Uganda", "Kenya", "Tanzania", "Rwanda"] },
  { flag: "https://flagcdn.com/w320/tz.png", country: "Tanzania", options: ["Kenya", "Uganda", "Tanzania", "Rwanda"] },
  { flag: "https://flagcdn.com/w320/rw.png", country: "Rwanda", options: ["Burundi", "Rwanda", "Uganda", "Tanzania"] },
  { flag: "https://flagcdn.com/w320/bi.png", country: "Burundi", options: ["Burundi", "Rwanda", "Tanzania", "Uganda"] },
  { flag: "https://flagcdn.com/w320/cd.png", country: "Democratic Republic of the Congo", options: ["Congo", "Zambia", "Democratic Republic of the Congo", "Angola"] },
  { flag: "https://flagcdn.com/w320/cg.png", country: "Republic of the Congo", options: ["Republic of the Congo", "Gabon", "Angola", "Cameroon"] },
  { flag: "https://flagcdn.com/w320/ga.png", country: "Gabon", options: ["Equatorial Guinea", "Gabon", "Congo", "Cameroon"] },
  { flag: "https://flagcdn.com/w320/gq.png", country: "Equatorial Guinea", options: ["Gabon", "Equatorial Guinea", "Cameroon", "Congo"] },
  { flag: "https://flagcdn.com/w320/cm.png", country: "Cameroon", options: ["Cameroon", "Gabon", "Nigeria", "Chad"] },
  { flag: "https://flagcdn.com/w320/ng.png", country: "Nigeria", options: ["Nigeria", "Cameroon", "Niger", "Ghana"] },
  { flag: "https://flagcdn.com/w320/ne.png", country: "Niger", options: ["Niger", "Mali", "Nigeria", "Chad"] },
  { flag: "https://flagcdn.com/w320/td.png", country: "Chad", options: ["Chad", "Niger", "Sudan", "Cameroon"] },
  { flag: "https://flagcdn.com/w320/cf.png", country: "Central African Republic", options: ["Chad", "Sudan", "Central African Republic", "Congo"] },
  { flag: "https://flagcdn.com/w320/ml.png", country: "Mali", options: ["Mali", "Niger", "Burkina Faso", "Senegal"] },
  { flag: "https://flagcdn.com/w320/bf.png", country: "Burkina Faso", options: ["Ghana", "Mali", "Burkina Faso", "Niger"] },
  { flag: "https://flagcdn.com/w320/gh.png", country: "Ghana", options: ["Ivory Coast", "Ghana", "Togo", "Nigeria"] },
  { flag: "https://flagcdn.com/w320/ci.png", country: "Ivory Coast", options: ["Ivory Coast", "Ghana", "Burkina Faso", "Liberia"] },
  { flag: "https://flagcdn.com/w320/gn.png", country: "Guinea", options: ["Guinea-Bissau", "Sierra Leone", "Guinea", "Liberia"] },
  { flag: "https://flagcdn.com/w320/gw.png", country: "Guinea-Bissau", options: ["Guinea-Bissau", "Guinea", "Senegal", "Sierra Leone"] },
  { flag: "https://flagcdn.com/w320/sl.png", country: "Sierra Leone", options: ["Liberia", "Guinea", "Sierra Leone", "Gambia"] },
  { flag: "https://flagcdn.com/w320/lr.png", country: "Liberia", options: ["Liberia", "Sierra Leone", "Ivory Coast", "Ghana"] },
  { flag: "https://flagcdn.com/w320/sn.png", country: "Senegal", options: ["Senegal", "Gambia", "Mali", "Guinea-Bissau"] },
  { flag: "https://flagcdn.com/w320/gm.png", country: "Gambia", options: ["Senegal", "Gambia", "Guinea-Bissau", "Mauritania"] },
  { flag: "https://flagcdn.com/w320/mr.png", country: "Mauritania", options: ["Senegal", "Mali", "Mauritania", "Niger"] },
  { flag: "https://flagcdn.com/w320/ma.png", country: "Morocco", options: ["Algeria", "Morocco", "Tunisia", "Mauritania"] },
  { flag: "https://flagcdn.com/w320/dz.png", country: "Algeria", options: ["Morocco", "Tunisia", "Libya", "Algeria"] },
  { flag: "https://flagcdn.com/w320/tn.png", country: "Tunisia", options: ["Tunisia", "Libya", "Algeria", "Morocco"] },
  { flag: "https://flagcdn.com/w320/ly.png", country: "Libya", options: ["Egypt", "Tunisia", "Sudan", "Libya"] },
  { flag: "https://flagcdn.com/w320/na.png", country: "Namibia", options: ["Namibia", "Botswana", "Angola", "South Africa"] },
  { flag: "https://flagcdn.com/w320/za.png", country: "South Africa", options: ["South Africa", "Namibia", "Botswana", "Lesotho"] },
  { flag: "https://flagcdn.com/w320/ls.png", country: "Lesotho", options: ["Lesotho", "Eswatini", "South Africa", "Botswana"] },
  { flag: "https://flagcdn.com/w320/sz.png", country: "Eswatini", options: ["South Africa", "Lesotho", "Eswatini", "Mozambique"] },
  { flag: "https://flagcdn.com/w320/mz.png", country: "Mozambique", options: ["Zimbabwe", "Mozambique", "Tanzania", "Malawi"] },
  { flag: "https://flagcdn.com/w320/zw.png", country: "Zimbabwe", options: ["Zimbabwe", "Zambia", "Mozambique", "Botswana"] },
  { flag: "https://flagcdn.com/w320/zm.png", country: "Zambia", options: ["Malawi", "Zambia", "Zimbabwe", "Angola"] },
  { flag: "https://flagcdn.com/w320/mw.png", country: "Malawi", options: ["Mozambique", "Zambia", "Tanzania", "Malawi"] },
  { flag: "https://flagcdn.com/w320/ao.png", country: "Angola", options: ["Namibia", "Zambia", "Angola", "Congo"] },
  { flag: "https://flagcdn.com/w320/mg.png", country: "Madagascar", options: ["Madagascar", "Mauritius", "Mozambique", "Comoros"] },
  { flag: "https://flagcdn.com/w320/km.png", country: "Comoros", options: ["Comoros", "Madagascar", "Seychelles", "Mauritius"] },
  { flag: "https://flagcdn.com/w320/sc.png", country: "Seychelles", options: ["Seychelles", "Mauritius", "Comoros", "Madagascar"] },
  { flag: "https://flagcdn.com/w320/mu.png", country: "Mauritius", options: ["Mauritius", "Madagascar", "Seychelles", "Comoros"] },
  { flag: "https://flagcdn.com/w320/cv.png", country: "Cape Verde", options: ["Cape Verde", "Senegal", "Mauritania", "Gambia"] },
  { flag: "https://flagcdn.com/w320/st.png", country: "São Tomé and Príncipe", options: ["São Tomé and Príncipe", "Gabon", "Angola", "Cameroon"] }
];